org.gradle.jvmargs=-Xms128m -Xmx1024m -Duser.timezone=UTC
org.gradle.welcome=never

kotlinVersion=2.1.20
kotlinLoggingVersion=7.0.7
mockitoKotlinVersion=5.4.0
springBootVersion=3.5.13
springDependencyManagementVersion=1.1.7
dockerComposePluginVersion=0.17.12

lalakiCentralVersion=1.2.5
ktlintVersion=14.0.1
ktlintToolVersion=1.8.0
ideaExt=1.1.10
nettyResolverDnsNativeMacOsVersion=4.2.0.Final

valtimoVersion=13.46.0.RELEASE
